CREATE TABLE PRO_PROCESO (
  PRO_ID INT AUTO_INCREMENT PRIMARY KEY,
  PRO_NOMBRE VARCHAR(60),
  PRO_PREFIJO VARCHAR(20)
);

CREATE TABLE TIP_TIPO_DOC (
  TIP_ID INT AUTO_INCREMENT PRIMARY KEY,
  TIP_NOMBRE VARCHAR(60),
  TIP_PREFIJO VARCHAR(20)
);

CREATE TABLE DOC_DOCUMENTO (
  DOC_ID INT AUTO_INCREMENT PRIMARY KEY,
  DOC_NOMBRE VARCHAR(60),
  DOC_CODIGO VARCHAR(60),
  DOC_CONTENIDO TEXT,
  DOC_ID_TIPO INT,
  DOC_ID_PROCESO INT,
  FOREIGN KEY (DOC_ID_TIPO) REFERENCES TIP_TIPO_DOC(TIP_ID),
  FOREIGN KEY (DOC_ID_PROCESO) REFERENCES PRO_PROCESO(PRO_ID)
);
